import type { Metadata } from "next";
import "./globals.css";
import ZohoDeskWidget from "@/components/ZohoDeskWidget";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ZohoDeskWidget />
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {children} */}
        <div></div>
      </body>
    </html>
  );
}
